apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: php-project
spec:
  selector:
    app: website-server
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32100
---

apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: php-project
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
