#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: local-storage
#provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: php-pv-claim
    namespace: php-project
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /php
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-wn2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pv-claim
  namespace: php-project
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
